import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Trophy,Search,Bell,Star,ExternalLink,RefreshCw,Check,ArrowLeft,ChevronRight} from 'lucide-react';
import {createCompetitionRepository,createCompetitionDemoRepository,COMPETITION_KINDS} from '../data/competitionRepository.js';
import {readPreference,writePreference} from '../data/preferences.js';
import {competitionMatchesQuery} from '../data/competitionRules.js';
import {safeUrl} from '../data/adapters.js';
import {Pager} from './WorkspaceParts.jsx';
import './competitions.css';

const timestamp=value=>value?new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'尚未检查';
const published=n=>n.date_verified&&n.published_at?n.published_at:'发布时间待核验';
function OfficialLink({url,children}){const href=safeUrl(url);return href?<a href={href} target="_blank" rel="noopener noreferrer">{children}<ExternalLink size={13}/></a>:<span className="muted">官网入口待核验</span>}
function ScoreTable({item}){if(!item.scores?.length)return <p className="competition-restriction">{item.recognition_note||'分值认定待确认'}</p>;return <table className="competition-scores"><caption className="sr-only">{item.name}截图参考分值</caption><thead><tr>{item.awards.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody><tr>{item.scores.map((x,i)=><td key={i}>{x==null?'未列明':x}</td>)}</tr></tbody></table>}

function ReferenceRules({item}){return <div className="competition-reference-rules"><p className="competition-policy">{item.reference_label}</p>{item.recognition_note&&<p className="competition-restriction">{item.recognition_note}</p>}{item.reference_rules?.map(rule=><section key={rule.category}><h3>{rule.category} · 截图列名级别：{rule.default_level}</h3><p>截图名称：{rule.screenshot_name}</p>{rule.levels.map(level=><div key={level.name}><h4>{level.name}</h4><ScoreTable item={{...level,name:item.name||item.competition_name}}/></div>)}{rule.notes.map(note=><p className="competition-rule-note" key={note}>{note}</p>)}</section>)}</div>}

export function CompetitionsPage({mode}){
 const repo=useMemo(()=>mode==='demo'?createCompetitionDemoRepository():createCompetitionRepository(),[mode]);
 const [college,setCollege]=useState(()=>readPreference('competition-college','cis')),[colleges,setColleges]=useState(null),[scope,setScope]=useState('college'),[category,setCategory]=useState('');
 const [section,setSection]=useState('catalog'),[query,setQuery]=useState(''),[group,setGroup]=useState(''),[competition,setCompetition]=useState(''),[kind,setKind]=useState(''),[tab,setTab]=useState('all'),[page,setPage]=useState(0);
 const [state,setState]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[revision,setRevision]=useState(0),[modal,setModal]=useState(null),[settingsDraft,setSettingsDraft]=useState(null);
 const dialog=useRef(null),lock=useRef(false),returnFocus=useRef(null),request=useRef(null),detailRequest=useRef(null),contextVersion=useRef(0);
 useEffect(()=>{const controller=new AbortController();repo.colleges(controller.signal).then(data=>{if(controller.signal.aborted)return;setColleges(data.items);if(!data.items.some(x=>x.id===college))setCollege(data.default_college)}).catch(e=>{if(!controller.signal.aborted){setError(e.message);setLoading(false)}});return()=>controller.abort()},[repo,revision]);
 useEffect(()=>{if(!colleges||!colleges.some(x=>x.id===college))return;const controller=new AbortController();request.current=controller;setLoading(true);setError('');Promise.all([repo.catalog(controller.signal,{college,scope:'all'}),repo.subscriptions(controller.signal),repo.notices({q:query,competition,kind,tab,page:section==='catalog'?0:page,college,scope,category:section==='notices'?category:''},controller.signal),repo.messages(section==='messages'?page:0,controller.signal,college),repo.crawl(controller.signal),repo.settings(controller.signal)]).then(([catalog,subscriptions,notices,messages,crawl,settings])=>{if(!controller.signal.aborted)setState({catalog,subscriptions,notices,messages,crawl,settings})}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[repo,!!colleges,college,scope,category,section,query,competition,kind,tab,page,revision]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')setRevision(v=>v+1)},state?.crawl.running?5000:60000);return()=>clearInterval(timer)},[state?.crawl.running]);
 useEffect(()=>{const el=dialog.current;if(modal){if(!el.open){returnFocus.current=document.activeElement;el.showModal()}}else if(el.open){el.close();returnFocus.current?.focus()}},[modal]);
 async function mutate(work){if(lock.current)return null;lock.current=true;setPending(true);setError('');try{const result=await work();setRevision(v=>v+1);return result}catch(e){if(e.name!=='AbortError')setError(e.message);return null}finally{lock.current=false;setPending(false)}}
 function nav(value){detailRequest.current?.abort();contextVersion.current++;setSection(value);setPage(0);setQuery('');setCompetition('');setKind('');setTab('all');setCategory('');setGroup('');setModal(null)}
 function filter(set,value){set(value);setPage(0)}
 async function follow(item){const ids=state.subscriptions.competitions;await mutate(()=>repo.follow(ids.includes(item.id)?ids.filter(x=>x!==item.id):[...ids,item.id]))}
 async function openNotice(id){detailRequest.current?.abort();const controller=new AbortController();detailRequest.current=controller;const version=contextVersion.current;const result=await mutate(()=>repo.notice(id,college,controller.signal));if(result&&!controller.signal.aborted&&version===contextVersion.current)setModal({type:'notice',item:result})}
 async function changeNotice(item,body){const version=contextVersion.current;const result=await mutate(()=>repo.update(item.id,body,college));if(result&&version===contextVersion.current)setModal(m=>m?.type==='notice'&&m.item.id===item.id?{...m,item:result}:m)}
 function changeCollege(value){request.current?.abort();detailRequest.current?.abort();contextVersion.current++;setState(null);setModal(null);setCollege(value);setScope('college');writePreference('competition-college',value);setPage(0);setCompetition('');setQuery('');setKind('');setGroup('');setCategory('');setError('')}
 useEffect(()=>()=>detailRequest.current?.abort(),[repo]);
 const profile=colleges?.find(x=>x.id===college);
 const settings=settingsDraft||state?.settings;
 const items=state?.catalog.items||[];
 const rows=items.filter(x=>(section==='following'||scope==='all'||x.reference_rules.length)&&(!category||x.reference_rules.some(r=>r.category===category))&&(!group||x.group===group)&&competitionMatchesQuery(x,query));
 const followed=state?.subscriptions.competitions||[];
 const visible=section==='following'?rows.filter(x=>followed.includes(x.id)):rows;
 const notices=state?.notices||{items:[],total:0},messages=state?.messages||{items:[],total:0,unread:0},crawl=state?.crawl||{};
 useEffect(()=>{if(section==='catalog'||section==='following')setPage(p=>Math.min(p,Math.max(0,Math.ceil(visible.length/12)-1)))},[visible.length,section]);
 useEffect(()=>{if(!loading&&(section==='notices'||section==='messages'))setPage(p=>Math.min(p,Math.max(0,Math.ceil((section==='messages'?messages.total:notices.total)/10)-1)))},[loading,section,messages.total,notices.total]);
 return <section className="competition-page" aria-label="赛事通知模块">
  <div className="competition-heading"><div><span className="eyebrow"><Trophy size={16}/> 学院赛事通知</span><h1>发现比赛，掌握参赛动态</h1><p>官方公告与综测参考分值，集中查看。</p></div><span className="competition-mode">{mode==='demo'?'独立演示数据':'官网真实数据'} · 当前为共享单用户模式</span></div>
  <div className="competition-college-toolbar glass"><label>选择学院 <select aria-label="选择学院" value={college} onChange={e=>changeCollege(e.target.value)}>{colleges?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{(section==='catalog'||section==='notices'&&!['following','favorite'].includes(tab))&&<label>浏览范围 <select aria-label="赛事范围" value={scope} onChange={e=>{filter(setScope,e.target.value);setCompetition('')}}><option value="college">当前学院赛事</option><option value="all">查看全部赛事</option></select></label>}{['catalog','following','notices'].includes(section)&&<label>规则类别 <select aria-label="规则类别" value={category} onChange={e=>{filter(setCategory,e.target.value);setCompetition('')}}><option value="">全部类别</option>{profile?.categories.map(x=><option key={x}>{x}</option>)}</select></label>}<p className="muted">{section==='following'||section==='messages'||section==='notices'&&['following','favorite'].includes(tab)?'关注、收藏和消息跨学院保留。':'赛事与官方公告共享，参考分值按学院展示。'}</p></div>
  <nav className="competition-nav glass" aria-label="赛事导航">{[['catalog','赛事目录'],['notices','官网通知'],['following','我的关注'],['messages','消息中心'],['collection','采集设置']].map(([id,label])=><button key={id} aria-label={label} aria-current={section===id?'page':undefined} onClick={()=>nav(id)}>{label}{id==='messages'&&messages.unread>0&&<b>{messages.unread}</b>}</button>)}</nav>
  {error&&<div className="competition-error" role="alert">{error}<button onClick={()=>setRevision(v=>v+1)}>重试</button></div>}
  {loading&&<p role="status" className="competition-loading">正在加载赛事…</p>}
  {state&&<>
   {(section==='catalog'||section==='following')&&<>
    <div className="competition-toolbar"><label className="directory-search"><Search size={16}/><input aria-label="搜索赛事" placeholder="赛事名称、简称" value={query} onChange={e=>filter(setQuery,e.target.value)}/></label><select aria-label="赛事分组" value={group} onChange={e=>filter(setGroup,e.target.value)}><option value="">全部分组</option><option>国家级</option><option>其他赛事</option></select><span className="muted">{visible.length} 场赛事</span></div>
    <p className="competition-policy">{state.catalog.policy.label}</p>
    <div className="competition-grid">{visible.slice(page*12,page*12+12).map(item=><article key={item.id} className="competition-card glass"><div className="competition-card-top"><span className="tag">{item.group}</span><span className={`competition-source-status ${item.status==='正常'?'is-normal':''}`}>{item.status}</span></div><button className="competition-title" onClick={()=>setModal({type:'competition',item})}>{item.name}</button>{item.reference_rules.map(r=><p className="muted" key={r.category}>{r.category} · {r.default_level}</p>)}{item.parent&&<p className="muted">{item.parent}</p>}{item.current_name&&item.current_name!==item.name&&<p className="muted">现用名称：{item.current_name}</p>}<ScoreTable item={item}/>{item.restriction&&<p className="competition-restriction">{item.restriction}</p>}<div className="competition-card-meta"><span>最近检查：{timestamp(item.last_checked)}</span><span>{item.notice_count} 条已采集</span></div><div className="competition-card-actions"><button className={`secondary ${followed.includes(item.id)?'is-followed':''}`} disabled={pending} onClick={()=>follow(item)}>{followed.includes(item.id)?<Check size={14}/>:<Star size={14}/>} {followed.includes(item.id)?'已关注':'关注赛事'}</button><button className="text-button" onClick={()=>{setSection('notices');setCompetition(item.id);setQuery('');setPage(0);setTab('all');setKind('');setCategory('');if(!item.reference_rules.length)setScope('all')}}>查看通知<ChevronRight size={14}/></button></div></article>)}</div>
    {!visible.length&&<div className="competition-empty glass"><Trophy/><h3>{section==='following'?'还没有关注的比赛':'没有匹配的赛事'}</h3><p>浏览赛事目录，选择你感兴趣的比赛。</p><button className="secondary" onClick={()=>nav('catalog')}>浏览全部赛事</button></div>}<Pager page={page} total={visible.length} size={12} onChange={setPage}/>
   </>}
   {section==='notices'&&<div className="glass competition-panel"><div className="section-head"><h2>官网参赛公告</h2><button className="text-button" onClick={()=>setRevision(v=>v+1)}><RefreshCw size={14}/>刷新</button></div><div className="competition-list-tabs">{[['all','全部'],['following','我的关注'],['favorite','我的收藏'],['unread','未读']].map(([value,label])=><button key={value} aria-pressed={tab===value} onClick={()=>{filter(setTab,value);setCategory('');setCompetition('')}}>{label}</button>)}</div><div className="competition-toolbar"><label className="directory-search"><Search size={15}/><input aria-label="搜索赛事通知" placeholder="搜索公告" value={query} onChange={e=>filter(setQuery,e.target.value)}/></label><select aria-label="筛选赛事" value={competition} onChange={e=>filter(setCompetition,e.target.value)}><option value="">全部赛事</option>{items.filter(x=>['following','favorite'].includes(tab)||scope==='all'||x.reference_rules.length).filter(x=>!category||x.reference_rules.some(r=>r.category===category)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select aria-label="通知类型" value={kind} onChange={e=>filter(setKind,e.target.value)}><option value="">全部类型</option>{COMPETITION_KINDS.map(x=><option key={x}>{x}</option>)}</select></div><p className="muted">最近一年 · 日期不明的公告标注待核验 · {notices.total} 条</p>
    {competition&&items.find(x=>x.id===competition)?.status!=='正常'&&<p className="competition-source-note">{items.find(x=>x.id===competition)?.error||`来源状态：${items.find(x=>x.id===competition)?.status}`}</p>}
    <div className="competition-notice-list">{notices.items.map(n=><article key={n.id}><div><span className="tag">{n.kind}</span><button className="competition-notice-title" disabled={pending} onClick={()=>openNotice(n.id)}>{n.title}</button><p>{n.competition_name} · {published(n)} · {n.read?'已读':'未读'}</p>{n.recognition_note&&<p className="competition-restriction">{n.recognition_note}</p>}</div><button className={`icon-button ${n.favorite?'saved':''}`} aria-label={`${n.favorite?'取消收藏':'收藏'}赛事通知：${n.title}`} aria-pressed={n.favorite} disabled={pending} onClick={()=>changeNotice(n,{favorite:!n.favorite})}><Star size={20}/></button></article>)}</div>
    {!notices.items.length&&<div className="competition-empty"><Bell/><h3>暂无符合筛选的已采集公告</h3><p>未接入和采集失败的来源，请在赛事目录中查看具体状态。</p></div>}<Pager page={page} total={notices.total} size={10} onChange={setPage}/>
   </div>}
   {section==='messages'&&<div className="glass competition-panel"><div className="section-head"><h2>赛事消息中心</h2><button className="secondary" disabled={pending||!messages.unread} onClick={()=>mutate(()=>repo.readMessage())}>全部标记已读</button></div><p className="muted">{messages.unread} 条未读 · 仅接收关注赛事的新公告，首次历史回填不推送。</p><div className="competition-message-list">{messages.items.map(m=><article key={m.id} className={m.read?'':'unread'}><button disabled={pending} onClick={()=>openNotice(m.notice_id)}><Bell size={19}/><span><strong>{m.title}</strong><small>{m.competition_name} · {timestamp(m.created_at)} · {m.read?'已读':'未读'}</small>{m.recognition_note&&<small className="competition-restriction">{m.recognition_note}</small>}</span></button><button className="text-button" disabled={pending||m.read} onClick={()=>mutate(()=>repo.readMessage(m.id))}>标记已读</button></article>)}</div>{!messages.items.length&&<div className="competition-empty"><Bell/><h3>暂无赛事消息</h3><p>关注比赛后，后续采集到的新公告会出现在这里。</p></div>}<Pager page={page} total={messages.total} size={10} onChange={setPage}/></div>}
   {section==='collection'&&<div className="glass competition-panel"><div className="section-head"><h2>赛事官网采集</h2><span className="tag">{crawl.running?'正在采集':'待命'}</span></div><p className="muted">首次回填最近365天。手动采集可选当前学院；定时采集始终覆盖全平台已接入来源。</p><div className="competition-crawl-actions"><button className="primary" disabled={pending||crawl.running||mode==='demo'} onClick={()=>mutate(()=>repo.start())}>采集全部已核验来源</button><button className="secondary" disabled={pending||crawl.running||mode==='demo'} onClick={()=>mutate(()=>repo.start(null,college))}>采集当前学院来源</button><button className="secondary" disabled={pending||!crawl.running} onClick={()=>mutate(()=>repo.stop())}>停止并保存进度</button><button className="text-button" onClick={()=>setRevision(v=>v+1)}>刷新进度</button></div><p>已处理 {crawl.completed||0} / {crawl.total||0} 个来源 · 最近完成：{timestamp(crawl.last_finished)}</p><div className="competition-schedule"><label>定时采集间隔（分钟）<input type="number" aria-label="赛事采集间隔" min="5" max="1440" value={settings.interval_minutes} onChange={e=>setSettingsDraft({...settings,interval_minutes:Number(e.target.value)})}/></label><label><input type="checkbox" checked={settings.scheduler_enabled} onChange={e=>setSettingsDraft({...settings,scheduler_enabled:e.target.checked})}/> 开启定时赛事采集</label><button className="secondary" disabled={pending} onClick={()=>mutate(async()=>{const saved=await repo.saveSettings(settings);setSettingsDraft(null);return saved})}>保存采集设置</button></div><div className="competition-source-list">{items.map(x=><div key={x.id}><strong>{x.name}</strong><span>{x.status} · {timestamp(x.last_checked)}</span>{x.error&&<p>{x.error}</p>}</div>)}</div></div>}
  </>}
  <dialog ref={dialog} className="competition-dialog" aria-label="赛事详情" onCancel={e=>{e.preventDefault();setModal(null)}} onClick={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="dialog-content"><button className="text-button competition-dialog-close" onClick={()=>setModal(null)}><ArrowLeft size={15}/> 返回赛事</button>{modal?.type==='competition'&&<><span className="tag">{modal.item.group}</span><h2>{modal.item.name}</h2>{modal.item.current_name&&modal.item.current_name!==modal.item.name&&<p>现用名称：{modal.item.current_name}</p>}<ReferenceRules item={modal.item}/>{modal.item.restriction&&<p className="competition-restriction">{modal.item.restriction}</p>}<div className="competition-detail-source"><h3>官方来源</h3><OfficialLink url={modal.item.official_url}>打开官方页面</OfficialLink><p>{modal.item.status} · {timestamp(modal.item.last_checked)}</p>{modal.item.error&&<p>{modal.item.error}</p>}{modal.item.sources.map(s=><div key={s.id}><strong>{s.name}</strong><OfficialLink url={s.evidence}>核验依据</OfficialLink><p>{s.status} · {s.baseline?'已建立更新基线':'首次回填中'}</p></div>)}</div><div className="dialog-actions"><button className="secondary" disabled={pending} onClick={()=>follow(modal.item)}>{followed.includes(modal.item.id)?'取消关注':'关注赛事'}</button><button className="primary" disabled={pending||crawl.running||mode==='demo'||!modal.item.sources.length} onClick={()=>mutate(()=>repo.start(modal.item.id))}>采集该赛事</button></div></>}
  {modal?.type==='notice'&&<><span className="tag">{modal.item.kind}{mode==='demo'?' · 示例':''}</span><h2>{modal.item.title}</h2><p className="dialog-meta">{modal.item.competition_name} · {published(modal.item)}</p><ReferenceRules item={modal.item}/><p className="muted">采集于 {timestamp(modal.item.collected_at)}</p><div className="competition-attachments">{modal.item.attachments.map((a,i)=><OfficialLink key={i} url={a.url}>{a.title||'官网附件'}</OfficialLink>)}</div><div className="dialog-actions"><button disabled={pending} className="secondary" onClick={()=>changeNotice(modal.item,{favorite:!modal.item.favorite})}>{modal.item.favorite?'取消收藏':'收藏通知'}</button><button disabled={pending||modal.item.read} className="secondary" onClick={()=>changeNotice(modal.item,{read:true})}>{modal.item.read?'已读':'标记已读'}</button>{safeUrl(modal.item.url)&&<a className="primary competition-original" href={safeUrl(modal.item.url)} target="_blank" rel="noopener noreferrer" onClick={()=>changeNotice(modal.item,{read:true})}>查看官网原文 <ExternalLink size={14}/></a>}</div></>}{error&&<p role="alert" className="error-text">{error}</p>}</div></dialog>
 </section>
}
