import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {BookOpen,GraduationCap,Users,Bell,CalendarDays,Layers} from 'lucide-react';
const TYPE_ICONS={study:BookOpen,work:GraduationCap,activity:Users,personal:Bell,other:Layers};
function EventIcon({category,allDay=false}){const Icon=allDay?CalendarDays:(TYPE_ICONS[category]||Layers);return <Icon className="event-type-icon" size={17} strokeWidth={2}/>;}
import {weekDates,eventLanes,moveEvent,clock,minutes,atDate} from '../data/schedule.js';
import {blankEvent,localDate} from '../data/calendarRepository.js';
const HOUR=52;
export function ScheduleWeek({selected,items,onSelect,onEdit,onMove,onComplete,pending,draft,initialScrollTop,onScrollChange,view='week',revealDate=0}){
 const days=view==='day'?[selected]:weekDates(selected),today=localDate(),scroll=useRef(null),shell=useRef(null),headings=useRef([]),gesture=useRef(null),frame=useRef(null);
 const [selection,setSelection]=useState(null),[gutter,setGutter]=useState(0),[selectingRange,setSelectingRange]=useState(false),suppressTouchClick=useRef(false);
 useEffect(()=>{const el=scroll.current;el.scrollTop=initialScrollTop??8*HOUR;const observer=new ResizeObserver(()=>setGutter(el.offsetWidth-el.clientWidth));observer.observe(el);const escape=e=>{if(e.key==='Escape')cancelSelection()};window.addEventListener('keydown',escape);return()=>{observer.disconnect();window.removeEventListener('keydown',escape);cancelAnimationFrame(frame.current)}},[]);
 useLayoutEffect(()=>{
  function reveal(){
   if(view!=='week'||innerWidth>999)return;
   const el=shell.current,button=headings.current[days.indexOf(selected)];
   if(el&&button)el.scrollLeft=Math.max(0,button.getBoundingClientRect().left-el.getBoundingClientRect().left+el.scrollLeft-54);
  }
  reveal();window.addEventListener('resize',reveal);return()=>window.removeEventListener('resize',reveal);
 },[selected,view,revealDate]);
 const weekend=date=>[0,6].includes(atDate(date).getDay());
 function renderEvent(event,allDay=false,style){
  const position=()=>shell.current?.querySelector(`[data-event-id="${event.id}"]`)?.getBoundingClientRect();
  const resize=edge=><span role="slider" tabIndex={0} aria-label={`调整${edge==='start'?'开始':'结束'}时间：${event.title}`} aria-valuemin={edge==='start'?0:event.start+15} aria-valuemax={edge==='start'?event.end-15:1439} aria-valuenow={edge==='start'?event.start:event.end} className={`event-resize ${edge}`} onPointerDown={e=>beginResize(e,event,edge)} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(['ArrowUp','ArrowDown'].includes(e.key)&&!pending){e.preventDefault();e.stopPropagation();const step=e.key==='ArrowUp'?-15:15;onMove(edge==='start'?{time:clock(Math.max(0,Math.min(event.end-15,event.start+step)))}:{end_time:clock(Math.min(1439,Math.max(event.start+15,event.end+step)))},event.id)}}}/>;
  return <div key={event.id} data-event-id={event.id} draggable={!allDay&&!pending} onDragStart={e=>{if(e.target.closest('input,.event-resize')){e.preventDefault();return}e.dataTransfer.setData('application/x-swu-event',String(event.id));e.dataTransfer.effectAllowed='move'}} className={`schedule-block ${allDay?'all-day-block':'timed'} type-${event.category||'other'} ${event.completed?'completed':''} ${draft?.id===event.id?'selected-event':''}`} style={style} title={`${event.title}${event.time?' '+event.time:''}${event.end_time?'–'+event.end_time:''}${event.location?' · '+event.location:''}`} onClick={e=>{e.stopPropagation();onEdit(event,position())}}>
   {!allDay&&resize('start')}
   <input className="block-completion" type="checkbox" aria-label={`完成日程：${event.title}`} disabled={pending} checked={event.completed} onPointerDown={e=>e.stopPropagation()} onClick={e=>e.stopPropagation()} onChange={()=>onComplete({completed:!event.completed},event.id)}/>
   <button className="event-open" onClick={e=>{e.stopPropagation();onEdit(event,position())}}><EventIcon category={event.category} allDay={allDay}/>
    <strong>{event.priority&&event.priority!=='normal'&&<span className={`task-priority ${event.priority}`} aria-label={event.priority==='high'?'高优先级':'低优先级'}>{event.priority==='high'?'!':'↓'}</span>}{event.title}</strong>
    {!allDay&&<><small>{event.time}{event.end_time?'–'+event.end_time:''}</small>{event.location&&<small>{event.location}</small>}</>}
   </button>
   {!allDay&&resize('end')}
  </div>;
 }
 function cancelSelection(){gesture.current=null;cancelAnimationFrame(frame.current);setSelection(null)}
 function minuteAt(el,y){return Math.max(0,Math.min(1439,(y-el.getBoundingClientRect().top)/HOUR*60))}
 function rangeOf(g){if(g.resize){const minute=Math.round(((g.edge==='start'?g.start:g.end)+(g.y-g.initialY)/HOUR*60)/15)*15;return {date:g.date,start:g.edge==='start'?Math.max(0,Math.min(g.end-15,minute)):g.start,end:g.edge==='end'?Math.min(1439,Math.max(g.start+15,minute)):g.end}}const a=Math.round(g.start/15)*15,b=Math.round(minuteAt(g.el,g.y)/15)*15;const start=Math.min(1425,Math.min(a,b));return {date:g.date,start,end:Math.min(1439,Math.max(start+15,a,b))}}
 function updateSelection(){const g=gesture.current;if(g){if(Math.abs(g.y-g.initialY)>3)g.moved=true;setSelection(rangeOf(g))}}
 function autoScroll(){const g=gesture.current;if(!g)return;const el=scroll.current,r=el.getBoundingClientRect();const delta=g.y<r.top+28?-8:g.y>r.bottom-28?8:0;if(delta){el.scrollTop+=delta;updateSelection()}frame.current=requestAnimationFrame(autoScroll)}
 function begin(e,date){if(pending||e.button!==0||e.target!==e.currentTarget)return;if(e.pointerType==='touch'&&!selectingRange){suppressTouchClick.current=false;return}e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);gesture.current={el:e.currentTarget,date,start:minuteAt(e.currentTarget,e.clientY),y:e.clientY,initialY:e.clientY,moved:false};updateSelection();frame.current=requestAnimationFrame(autoScroll)}
 function beginResize(e,event,edge){e.preventDefault();e.stopPropagation();if(pending)return;const el=e.currentTarget.closest('.week-day-column');e.currentTarget.setPointerCapture(e.pointerId);gesture.current={el,date:event.date,start:minutes(event.time),end:event.end_time?minutes(event.end_time):Math.min(1439,minutes(event.time)+60),event,edge,resize:true,y:e.clientY,initialY:e.clientY,moved:false};updateSelection();frame.current=requestAnimationFrame(autoScroll)}
 function anchorFor(el,minute){const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top+minute/60*HOUR}}
 function finish(e){const g=gesture.current;if(!g)return;g.y=e.clientY;const range=rangeOf(g);cancelSelection();if(g.resize){if(g.moved)onMove({time:clock(range.start),end_time:clock(range.end)},g.event.id);return}if(e.pointerType==='touch'){setSelectingRange(false);suppressTouchClick.current=true}if(g.moved)onEdit({...blankEvent(g.date),time:clock(range.start),end_time:clock(range.end)},anchorFor(g.el,range.start));else create(g.date,e.clientY-g.el.getBoundingClientRect().top,g.el)}
 function create(date,y,el){const minute=Math.max(0,Math.min(1380,Math.floor(y/HOUR*4)*15));onEdit({...blankEvent(date),time:clock(minute),end_time:clock(minute+60)},el?anchorFor(el,minute):null)}
 return <div ref={shell} className={`schedule-week ${view==='day'?'is-day':'is-week'} ${selectingRange?'selecting-range':''}`} aria-label={view==='day'?'日时间表':'周时间表'} style={{'--week-gutter':`${gutter}px`,'--schedule-days':days.length}}><div className="time-grid-tools"><span>{selectingRange?'拖动选择时间':'滑动浏览 · 轻点添加'}</span><button disabled={pending} aria-pressed={selectingRange} onClick={()=>{cancelSelection();suppressTouchClick.current=false;setSelectingRange(v=>!v)}}>{selectingRange?'退出选择':'选择时段'}</button></div><div className="week-heading" style={{marginRight:gutter}}><span/>{days.map((d,i)=><button key={d} ref={el=>{headings.current[i]=el}} className={`${d===today?'today':''} ${weekend(d)?'weekend':''}`} onClick={()=>onSelect(d)} aria-pressed={d===selected}><small>周{'日一二三四五六'[atDate(d).getDay()]}</small><span className="week-date"><strong>{Number(d.slice(-2))}</strong><time>{Number(d.slice(5,7))}月{Number(d.slice(-2))}日</time></span></button>)}</div>
 <div className="week-all-day" style={{marginRight:gutter}}><span>全天</span>{days.map(d=><div key={d} className={weekend(d)?'weekend':''}><button className="add-all-day" aria-label={`添加 ${d} 全天日程`} disabled={pending} onClick={e=>onEdit(blankEvent(d),e.currentTarget.getBoundingClientRect())}>＋</button>{items.filter(e=>e.date===d&&!e.time).map(e=>renderEvent(e,true))}</div>)}</div>
 <div className="week-scroll" ref={scroll} onScroll={e=>onScrollChange?.(e.currentTarget.scrollTop)}><div className="week-hours" style={{height:24*HOUR}}><div className="hour-labels">{Array.from({length:24},(_,h)=><span key={h} style={{top:h*HOUR}}>{String(h).padStart(2,'0')}:00</span>)}</div>{days.map(d=><div className={`week-day-column ${weekend(d)?'weekend':''} ${d===today?'current-day':''}`} role="group" tabIndex={0} aria-label={`${d} 时间段，点击或按 Enter 添加日程`} key={d} style={{backgroundSize:`100% ${HOUR}px`}} onClick={e=>{if(e.target!==e.currentTarget||e.nativeEvent.pointerType!=='touch'||pending)return;if(suppressTouchClick.current){suppressTouchClick.current=false;return}create(d,e.clientY-e.currentTarget.getBoundingClientRect().top,e.currentTarget)}} onPointerDown={e=>begin(e,d)} onPointerMove={e=>{if(gesture.current){gesture.current.y=e.clientY;updateSelection()}}} onPointerUp={finish} onPointerCancel={cancelSelection} onLostPointerCapture={()=>{if(gesture.current)cancelSelection()}} onKeyDown={e=>{if(e.target===e.currentTarget&&e.key==='Enter'&&!pending)onEdit({...blankEvent(d),time:'09:00',end_time:'10:00'})}} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-swu-event'))e.preventDefault()}} onDrop={e=>{e.preventDefault();const item=items.find(x=>x.id===Number(e.dataTransfer.getData('application/x-swu-event')));if(item&&!pending)onMove(moveEvent(item,d,(e.clientY-e.currentTarget.getBoundingClientRect().top)/HOUR*60),item.id)}}>
 {eventLanes(items.filter(e=>e.date===d&&e.time)).map(event=>renderEvent(event,false,{top:event.start/60*HOUR,height:Math.max(18,(event.end-event.start)/60*HOUR-3),left:`calc(${event.lane/event.lanes*100}% + 5px)`,width:`calc(${100/event.lanes}% - 10px)`}))}
 {draft&&!draft.id&&draft.date===d&&draft.time&&<div className="draft-time-block" style={{top:minutes(draft.time)/60*HOUR,height:Math.max(18,((draft.end_time?minutes(draft.end_time):minutes(draft.time)+60)-minutes(draft.time))/60*HOUR)}}><span>{draft.time}{draft.end_time?'–'+draft.end_time:''}</span><strong>{draft.title}</strong></div>}
 {selection?.date===d&&<div className="time-selection" style={{top:selection.start/60*HOUR,height:(selection.end-selection.start)/60*HOUR}}><span>{clock(selection.start)}–{clock(selection.end)}</span></div>}
 {d===today&&<div className="now-line" aria-hidden="true" style={{top:(new Date().getHours()+new Date().getMinutes()/60)*HOUR}}/>}
 </div>)}</div></div></div>;
}
